root: true


extends:
  - bsara

parserOptions:
  sourceType: module


rules:
  # Possible Errors
  # ----------------------------------------------------------

  # Disabled
  no-console: off
  no-debugger: off



  # Node.js and CommonJS
  # ----------------------------------------------------------

  # Disabled
  global-require: off
